### ISSUE TITLE
Newly spawned jupyter dockers can't connect to hub - network problem?

### ISSUE THREAD

**Issue by e-t-k** [rcurrie/scell#1]
Per @jpfeil , upon starting his personal jupyter, the page shows an error:
```
500 : Internal Server Error
The error was:
Failed to connect to Hub API at 'http://jupyterhub:8080/hub/api'.  
Is the Hub accessible at this URL (from host: 9a96b16c8fea)?
```

My server, which was 14 days old, failed to have this problem and was fully working.

I was able to reproduce by stopping and restarting my jupyter server via the web gui at which point I consistently got the same error.

From inside the docker: 
```
# ping jupyterhub
ping: unknown host
```

**Workaround** : hardcoding the hub_jupyterhub_1 IP into /etc/hosts on the docker client allowed me access to my notebooks again: `172.18.0.6 jupyterhub`

Thanks!

**Comment by e-t-k** [comment]
Additionally, can't apt-get update from inside a docker; pinging the package website works by IP but not by domain.

```sh
root@ca0cd885d841:~/work# ping 151.101.0.204
PING 151.101.0.204 (151.101.0.204): 56 data bytes
64 bytes from 151.101.0.204: icmp_seq=0 ttl=50 time=5.347 ms
64 bytes from 151.101.0.204: icmp_seq=1 ttl=50 time=4.068 ms
^C--- 151.101.0.204 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 4.068/4.707/5.347/0.640 ms
root@ca0cd885d841:~/work# ping cdn-fastly.deb.debian.org
ping: unknown host
```

Workaround: edit /etc/resolv.conf and add google's nameservers at the end
`nameserver 8.8.8.8 nameserver 8.8.4.4`

**Comment by rcurrie** [comment]
I’ve been trying to re-create this on my dev box with no luck. Jupyter run on its own, and from jupyter quite happily resolves. When I tilted up this latest version of the hub it all worked fine as well. Will keep spelunking…

**Comment by rcurrie** [comment]
Ok, I think I've sorted it all out. Explicitly using the older dockerspawner and updating vs. overwritting a dictionary entry in the jupyterhub config. Clean build and docker-compose up, I've stopped and started my server many times, and verified you should be able to sudo apt-get update and sudo apt-get install in the container. @e-t-k @jpfeil let me know if it goes ok at which point I'll close this.

**Comment by e-t-k** [comment]
@rcurrie just exercised these successfully & looks great on my end. Thanks so much.
